### ISSUE TITLE
Integrating browser-headers with Angular4

### ISSUE THREAD

**Issue by sandroverna** [improbable-eng/js-browser-headers#12]
hi improbable,
is possible to write a Plunker code for integration and use in a angular4 component?

if add
**import { BrowserHeaders } from 'browser-headers';**
in app.module.ts
and insert:
**providers: [
           ...,
           BrowserHeaders,
           ...,
]**
this error message do appear in console
**Uncaught Error: Can't resolve all parameters for BrowserHeaders: (?, ?).**

**Comment by MarcusLongmuir** [comment]
Apologies for the long delay. If you're still having an issue with this then please re-open with more context if available. 

However, from what I can tell this might not be the best place to raise this issue.
