### ISSUE TITLE
Enable splitValues by default

### ISSUE THREAD

**Issue by johanbrandhorst** [improbable-eng/js-browser-headers#21]
Hi!

While investigating inconsistencies between the Go gRPC client and the Improbable gRPC-Web client, I found that the Go gRPC server now returns pre-announcement trailers to the client. This started happening sometime between 1.9.2 and 1.18.0, I haven't been able to figure out when yet.

To make this consistent with the gRPC-Web client I've been experimenting with sending these trailer pre-announcement headers to the client by _not_ skipping them in the proxy (basically, commenting out these lines: 
* https://github.com/improbable-eng/grpc-web/blob/0c7a81a25d11e97972b5b6e6e61312fd7ad6413a/go/grpcweb/grpc_web_response.go#L74-L77
* https://github.com/improbable-eng/grpc-web/blob/0c7a81a25d11e97972b5b6e6e61312fd7ad6413a/go/grpcweb/grpc_web_response.go#L100-L103
* https://github.com/improbable-eng/grpc-web/blob/0c7a81a25d11e97972b5b6e6e61312fd7ad6413a/go/grpcweb/grpc_web_response.go#L141-L144
* https://github.com/improbable-eng/grpc-web/blob/master/go/grpcweb/websocket_wrapper.go#L58-L61
* https://github.com/improbable-eng/grpc-web/blob/master/go/grpcweb/websocket_wrapper.go#L78-L81

This causes a few problems for the client, but specifically for this repo, it means that unless `splitValues`https://github.com/improbable-eng/js-browser-headers/blob/14a73f4ebfe550ea9a88d9f6ed37b6a48cc5eec7/src/BrowserHeaders.ts#L34

is set to "true", it turns the pre-announcement trailer headers from
```
trailer: Grpc-Status
trailer: Grpc-Message
trailer: Grpc-Status-Details-Bin
```
to
```
trailer: Grpc-Status, Grpc-Message, Grpc-Status-Details-Bin 
```

I request that we turn this on by default. I'm sure there's a good reason it's off by default, but I don't really understand why.

I've only tested this with `fetch` on Chromium, but since this library is transport agnostic I hope it's okay.

**Comment by MarcusLongmuir** [comment]
It's set to false by default because whilst it's common behaviour for servers to comma-separate values for the same header key it's not the standard behaviour of the Headers class - likely because you might have a key that contains a single value that is actually a comma-separated string?

In the case of usage with `grpc-web`, can we not just set it to `true`? In that case it might be safer to make some more assumptions about the values of the trailers.

**Comment by johanbrandhorst** [comment]
That seems a reasonable compromise, I'll close this and open a separate issue in grpc-web.
